# Generated by Django 5.2.6 on 2025-09-04 15:17

import transcriber.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=transcriber.models.get_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('transcribed', 'Transcribed'), ('error', 'Error')], default='uploaded', max_length=20)),
                ('raw_transcription', models.TextField(blank=True, null=True)),
                ('corrected_transcription', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
